# Generated by Django 4.1.13 on 2024-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourDownloads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedwork',
            name='id',
        ),
        migrations.AddField(
            model_name='completedwork',
            name='completedWork_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
