# Generated by Django 4.1.13 on 2024-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourDownloads', '0004_alter_completedwork_completedwork_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='completedWork_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
