# Generated by Django 5.0 on 2023-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20171118_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='this_job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
