# Generated by Django 4.1.13 on 2024-03-08 07:39

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_this_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='this_job',
            name='attach_files',
            field=models.FileField(blank=True, null=True),
        ),
    ]
