# Generated by Django 4.1.13 on 2024-03-18 13:06

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_this_job_attach_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='this_job',
            name='attach_files',
            field=models.FileField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='this_job',
            name='user',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
