# Generated by Django 4.1.13 on 2024-03-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_this_job_attach_files_alter_this_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='this_job',
            name='attach_files',
        ),
    ]
