# Generated by Django 4.1.13 on 2024-03-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finished_Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Completed_tasks/'),
        ),
    ]
