# Generated by Django 4.1.13 on 2024-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finished_Tasks', '0002_alter_completedtasks_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='completedTasks',
            new_name='completedTaskss',
        ),
    ]
