# Generated by Django 4.1.13 on 2024-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finished_Tasks', '0003_rename_completedtasks_completedtaskss'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtaskss',
            name='taskNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
