# Generated by Django 4.1.13 on 2024-03-15 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finished_Tasks', '0004_completedtaskss_tasknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtaskss',
            name='taskNumber',
        ),
    ]
