# Generated by Django 5.0 on 2024-01-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='clientName',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Currency',
            field=models.CharField(choices=[('$', 'USD')], default='$', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Literature', 'Literature'), ('Graphic Design', 'Graphic Design'), ('Research', 'Research')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
