# Generated by Django 5.0 on 2024-01-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_remove_transaction_clientname_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Currency',
            field=models.CharField(choices=[('$', 'USD'), ('Ksh', 'KSH')], default='$', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Current', 'Current'), ('Paid', 'Paid')], default='Current', max_length=250),
        ),
    ]
