# Generated by Django 5.0 on 2024-01-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_alter_transaction_currency_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paymentTerms',
            field=models.CharField(choices=[('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='14 days', max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(choices=[('Current', 'Current'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Current', max_length=250),
        ),
    ]
