# Generated by Django 5.0 on 2024-01-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_transaction_paymentterms_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paymentTerms',
            new_name='paymentPeriod',
        ),
    ]
