# Generated by Django 5.0 on 2024-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_rename_paymentterms_transaction_paymentperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
