# Generated by Django 5.0 on 2024-01-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0008_invoice_delete_client_delete_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_four',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_four_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_four_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_four_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_one_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_three',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_three_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_three_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_three_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_two',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_two_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_two_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_two_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Budget',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Literature', 'Literature'), ('Graphic Design', 'Graphic Design'), ('Research', 'Research')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Task',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emailAddress',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
