# Generated by Django 5.0 on 2024-01-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0011_alter_invoice_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Budget',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
    ]
