# Generated by Django 5.0 on 2024-01-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0012_alter_invoice_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Literature', 'Literature'), ('Graphic Design', 'Graphic Design'), ('Research', 'Research'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentPeriod',
            field=models.CharField(blank=True, choices=[('14 days', '14 days'), ('30 days', '30 days')], max_length=200, null=True),
        ),
    ]
