# Generated by Django 5.0 on 2024-02-02 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_alter_this_job_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.this_job')),
                ('post_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
