# Generated by Django 4.1.13 on 2024-03-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatmessage_thread_remove_chatnotification_chat_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
